### ISSUE TITLE
add swagger!

### ISSUE THREAD

**Issue by antonkulaga** [biocypher/biochatter-server#16]
Dealing with your REST api is painful because you do not have swagger. I see you are using flask. If you switch to flask-based https://github.com/tiangolo/fastapi you will get swagger for free with minimal effort

**Comment by slobentanzer** [comment]
Hi @antonkulaga,
I agree, as already recorded in #1.

I am not a web tech expert; maybe @fengsh27 has time to look into it. Alternatively, if this is easy for you @antonkulaga, you could consider a PR (would be very welcome). The BioChatter paper is in review, so if we merge this feature in the next ~3 weeks, I can offer adding you to the coauthors/consortium in the revision. The two of you could also work together if you have the time/motivation. I think this would be a really nice usability improvement indeed. Let me know how we should do this. :)

**Comment by antonkulaga** [comment]
@slobentanzer , @fengsh27 , please take a look at my PR https://github.com/biocypher/biochatter-server/pull/17 I also give a screenshot, I belive with swagger exploring API becomes way easier.

**Comment by slobentanzer** [comment]
Perfect, thanks a lot! Waiting for @fengsh27 to take a look before merging, but looks good. :)
