### ISSUE TITLE
Server: return metadata for RAG

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter-server#9]

**Comment by slobentanzer** [comment]
@fengsh27 does the biochatter-server already return metadata?

**Comment by fengsh27** [comment]
@slobentanzer No, I don't think it has been implemented in biochatter-server. Addtionally, it seems, in biochatter, we also have some work to do to return meta data.

**Comment by slobentanzer** [comment]
OK, thanks for clarifying. I think passing metadata of RAG events from BioChatter and visualising them in the frontend is the last big task we have to accomplish before submission (or at least would be very nice to have for transparency reasons).

**Comment by slobentanzer** [comment]
@fengsh27 this is addressed, right?
